### ISSUE TITLE
想请教一下 helper 中的 sign 是怎么逆向出来的

### ISSUE THREAD

**Issue by huyhi** [ReaJason/xhs#10]
本人试图对小红书的 JavaScript 代码进行逆向，但是发现这部分的代码是混淆过的，想请教下这块是怎么分析的

**Comment by ReaJason** [comment]
用 Chrome DevTool debug 进去一个一个变量替换出来的，还挺费时间的，网上没找到针对这种的反混淆工具。

**Comment by huyhi** [comment]
OK，收到谢谢
