### ISSUE TITLE
report_note_metrics方法时好时坏

### ISSUE THREAD

**Issue by hjhjhghghg** [ReaJason/xhs#108]
这个接口除了note_id,user_id,viewer_user_id以外，还需要替换生成新的web_session，可是目前的代码中，启动playwright实例后，web_session的值就不会变化了，导致report_note_metrics接口不稳定，有什么好的方法，可以生成web_session吗

**Comment by ReaJason** [comment]
可以自己启动一个 playwright，打开小红书页，每刷新一次就是一个新的 cookie，然后 `client.cookie = new_cookie` 可以替换
