### ISSUE TITLE
请问如何正确获取cookie

### ISSUE THREAD

**Issue by TigerBest** [ReaJason/xhs#11]
你好，我比较小白。。请见谅。
我是从52论坛来的，你开发的reatool软件，扫码登陆很好用，但我想试试cookie登录。
我把开发者模式-网络下找到的cookie值粘贴到软件里好像没用，二维码一直在刷新。
![image](https://user-images.githubusercontent.com/47245203/236986510-4e92967b-ed6c-4a41-a5ea-ea18699b3107.png)
感觉是我没有正确获取cookie，请教一下该怎么获取。
谢谢！

**Comment by TigerBest** [comment]
![image](https://github.com/ReaJason/xhs/assets/47245203/a220a2f4-617a-4afb-a1d0-cf5b90670de0)
我把所有搜到的带有“web_session”参数的cookie都试过了（复制粘贴值），还是不行。以及用的就是1.0.4版本。

**Comment by hyq1995** [comment]
你python的版本有没有3.9以上，应该是版本问题。我clone下来项目，升级了python3.9.5版本，可以运行。

**Comment by ReaJason** [comment]
PySide6 客户端在解决签名问题之前不会再更新了，因为已经废了
