### ISSUE TITLE
About Save video or image

### ISSUE THREAD

**Issue by fangsiff** [ReaJason/xhs#12]
I installed the latest version: 0.1.9.
When I try to download files by note id, xhs client will exit with exception:

`XhsClient' object has no attribute '_get_img_urls_from_note`

I searched from source code, class XhsClient has no protect function `_get_video_url_from_note` and `_get_img_urls_from_note`

Should I intall any other requirements?

**Comment by ReaJason** [comment]
The issue has been resolved in version 0.2.0. 
Please update the version with `pip install -U xhs`.
Thanks for your feedback ♥.
