### ISSUE TITLE
发布视频接口：{'code': -100, 'errCode': -100, 'success': False, 'msg': '用户未登录'}

### ISSUE THREAD

**Issue by xxnioo** [ReaJason/xhs#131]
cookie获取到了，签名也成功了，普通图文笔记也发成功了

但是发布视频接口失败了，提示未登录，请问大佬这是什么问题？

**Comment by xxnioo** [comment]
test_create_video_note 这个接口

**Comment by xxnioo** [comment]
视频是3.1M，没有超过5M

**Comment by xxnioo** [comment]
我换test_create_video_note_with_cover这个接口，传了封面，就可以了

**Comment by liujingyangself** [comment]
兄弟，你咋做的，能不能给贴个代码，我怎么运行怎么出错，崩溃了。。。
