### ISSUE TITLE
关于多账号同时登录的问题

### ISSUE THREAD

**Issue by xxnioo** [ReaJason/xhs#132]
1、每次扫码登录会不会把之前的号顶掉，支持同时登录吗？
2、每个cookie的有效期大概多久，怎么能感知过期了
3、多账号共用一个docker签名服务的a1可以吗？

**Comment by ReaJason** [comment]
1. 对于一个 XhsClient 来说，只能存在一个账号，但是每次扫描登录完之后获取的 cookie 认证信息是有效的，可以使用一个 XhsClient 来登录多个账号，不会被顶掉。
2. cookie 主要看 web_session 具体可以看过期时间，Max-Age=31536000，刚看了一下还是一年
3. 可以的，把 cookie 中的 a1 设置成一个就行

**Comment by xxnioo** [comment]
> 1. 对于一个 XhsClient 来说，只能存在一个账号，但是每次扫描登录完成后获取的 cookie 认证信息是有效的，可以使用一个 XhsClient 来登录多个账号，不会被顶掉。
> 2. cookie主要看web_session具体可以观看一段时间，Max-Age=31536000，刚看还是一年
> 3. 可以的，把cookie中的a1设置成一个就行

感谢在放假之前回复 666

**Comment by wangcker** [comment]
共用a1不会被限流吗
