### ISSUE TITLE
I want to know the difference between these two functions.

### ISSUE THREAD

**Issue by hezhenfan** [ReaJason/xhs#135]
def get_note_by_id(self, note_id: str):
        """
        :param note_id: note_id you want to fetch
        :type note_id: str
        :rtype: dict
        """
        data = {"source_note_id": note_id, "image_scenes": ["CRD_WM_WEBP"]}
        uri = "/api/sns/web/v1/feed"
        res = self.post(uri, data)
        return res["items"][0]["note_card"]

    def get_note_by_id_from_html(self, note_id: str):
        """get note info from "https://www.xiaohongshu.com/explore/" + note_id,
        and the return obj is equal to get_note_by_id

        :param note_id: note_id you want to fetch
        :type note_id: str
        """

**Comment by ReaJason** [comment]
get_note_by_id 这个接口需要签名，通过 api 拿数据，和其他接口同等限制频率。

get_note_by_id_from_html 这个接口不需要签名，直接从 HTML 中提取。另外之前这个接口未授权也能拿到数据，不过后来修复了。
