### ISSUE TITLE
每个关键词的搜索条数限制是220条吗

### ISSUE THREAD

**Issue by Bit-sjw** [ReaJason/xhs#17]

**Comment by Bit-sjw** [comment]
![image](https://github.com/ReaJason/xhs/assets/111261712/8af48cef-d04b-4e99-9cc6-8dc69e10e149)
今天使用发现创建客户端对象出现这个异常是因为没有使用sign吗
![image](https://github.com/ReaJason/xhs/assets/111261712/ec4773ba-d1de-4403-8c11-45712b5e3634)

**Comment by stivensss** [comment]
我也遇到了这个问题，
![image](https://github.com/ReaJason/xhs/assets/30815786/0ba943e4-a313-430a-b962-971c0210e79c)

**Comment by ajiansoft** [comment]
xhs.exception.DataFetchError: 浏览器异常，请尝试关闭/卸载风险插件或重启试试！

**Comment by ReaJason** [comment]
> 今天使用发现创建客户端对象出现这个异常是因为没有使用sign吗

不是的哦，是签名算法失效了， the same as #19
