### ISSUE TITLE
欢迎使用的小伙伴提供修改建议，以及功能添加

### ISSUE THREAD

**Issue by ReaJason** [ReaJason/xhs#2]
- [x] 添加批量获取用户所有笔记的接口
- [x] #5

**Comment by ReaJason** [comment]
目前正在使用 PySide6 做用户界面的爬虫操作，不过不清楚实际需要那些功能。目前考虑的主要就是上面所添加的两个接口，还没想到其他有价值的功能。

**Comment by niostack** [comment]
自动回复评论能做吗

**Comment by ReaJason** [comment]
> 自动回复评论能做吗

可以的，有回复评论的接口，见 [L397](https://github.com/ReaJason/xhs/blob/master/xhs/core.py#L397-L397)

**Comment by niostack** [comment]
> > 自动回复评论能做吗
> 
> 可以的，有回复评论的接口，见 [L397](https://github.com/ReaJason/xhs/blob/master/xhs/core.py#L397-L397)

貌似可以做个机器人了，有没有办法监听到用户评论的事件的

**Comment by ReaJason** [comment]
> 貌似可以做个机器人了，有没有办法监听到用户评论的事件的

从目前已有接口来说，只能通过轮询获取所有笔记的评论与上一次获取的比较，来判断是否有新的评论产生，暂无便捷的方式。（或者有认识的小红书的员工提供一点能用的接口，hhhh）

**Comment by Aaronchenn** [comment]
大佬666.
大佬可以做一个模拟登陆么？比如获取web二维码，然后显示，扫码。获取到登录后的cookie。
现在还是要手动输入cookie

**Comment by Aaronchenn** [comment]
现在大佬知道接口请求的频次是多少么？感觉稍微快一点点，就会被检测。5s一次？

**Comment by Aaronchenn** [comment]
> 大佬666. 大佬可以做一个模拟登陆么？比如获取web二维码，然后显示，扫码。获取到登录后的cookie。 现在还是要手动输入cookie

噢噢噢对不起，我看到接口了，有qr code了，谢谢大佬。

**Comment by ReaJason** [comment]
> 

不知道，没测过，不过好像获取评论的接口容易被检测，而获取用户笔记的接口能一直请求很多次都没事

**Comment by a936919** [comment]
可以加下获取批量获取用户的收藏笔记和点赞的笔记吗
感谢！

**Comment by ReaJason** [comment]
> 

可以的，不过好像基本没看到有用户把点赞的笔记列表展示出来的，基本都只看到一个收藏的

**Comment by a936919** [comment]
> > 可以加下获取批量获取用户的收藏笔记和点赞的笔记吗
> > 感谢！
> 
> 可以的，不过好像基本没看到有用户把点赞的笔记列表展示出来的，基本都只看到一个收藏的

好像就是 点赞笔记应该只有自己的能看见 只加一个获取自己点赞的笔记的函数就行了

**Comment by ReaJason** [comment]
> 好像就是 点赞笔记应该只有自己的能看见 只加一个获取自己点赞的笔记的函数就行了
已添加，请更新一下，pip install -U xhs

**Comment by ReaJason** [comment]
> 获取用户全部的笔记的函数里面 好像没有返回笔记创建时间和最近更新时间 我看获取单个笔记里面有这两项返回值 大佬有时间可以把这两项加上

已添加，请更新一下，感谢反馈🌹

**Comment by pengdaqian2020** [comment]
调用 https://edith.xiaohongshu.com/api/sns/web/v1/login/activate 自动获取cookie
ref: http://www.lxspider.com/?p=257

**Comment by ReaJason** [comment]
> 调用 https://edith.xiaohongshu.com/api/sns/web/v1/login/activate 自动获取cookie ref: http://www.lxspider.com/?p=257

这个文章好像有访问权限。我看到过这个接口，这个接口会在退出登录的时候触发替换掉 web_session，其实返回的 web_session 是未登录状态的，也就是无法使用的。

**Comment by pengdaqian2020** [comment]
> > 调用 https://edith.xiaohongshu.com/api/sns/web/v1/login/activate 自动获取cookie ref: http://www.lxspider.com/?p=257
> 
> 这个文章好像有访问权限。我看到过这个接口，这个接口会在退出登录的时候触发替换掉 web_session，其实返回的 web_session 是未登录状态的，也就是无法使用的。

未登录状态目前看也能获取笔记详情和用户详情

**Comment by ReaJason** [comment]
> 调用 https://edith.xiaohongshu.com/api/sns/web/v1/login/activate 自动获取cookie ref: http://www.lxspider.com/?p=257

这个接口请求需要 gid 和已签名的 a1，我发现 /api/sec/v1/shield/webprofile 的有个很长的参数很难解密的亚子

**Comment by big-thousand** [comment]
图片链接可以替换为无水印的链接

```
https://ci.xiaohongshu.com/${traceId}
```

**Comment by ReaJason** [comment]
> 图片链接可以替换为无水印的链接
> 
> ```
> https://ci.xiaohongshu.com/${traceId}
> ```

目前已经是无水印的啦，[#L95](https://github.com/ReaJason/xhs/blob/master/xhs/core.py#L95)

**Comment by Bit-sjw** [comment]
获取某个用户所有笔记的函数，有时候会因为碰到一些有问题的笔记而中断，好像报错是笔记内容异常，对于这种情况能设置跳过异常的笔记吗。或许是0.1.5还没有这个功能？今天看到楼主升级到0.1.8了

**Comment by Bit-sjw** [comment]
> > 
> 
> 不知道，没测过，不过好像获取评论的接口容易被检测，而获取用户笔记的接口能一直请求很多次都没事

获取用户所有笔记也需要设置3~5s的间隔吧大佬。我没有设置间隔每次都被封IP了

**Comment by ReaJason** [comment]
> 获取某个用户所有笔记的函数，有时候会因为碰到一些有问题的笔记而中断，好像报错是笔记内容异常，对于这种情况能设置跳过异常的笔记吗。或许是0.1.5还没有这个功能？今天看到楼主升级到0.1.8了

目前还没有设置那个跳过异常的笔记

**Comment by ReaJason** [comment]
> > > 
> > 
> > 
> > 不知道，没测过，不过好像获取评论的接口容易被检测，而获取用户笔记的接口能一直请求很多次都没事
> 
> 获取用户所有笔记也需要设置3~5s的间隔吧大佬。我没有设置间隔每次都被封IP了

间隔好像没用，我测试固定获取到 100 个左右会被封三到六分钟，只能等待解封

**Comment by ReaJason** [comment]
> 

最新 0.2.0 支持跳过异常笔记了

**Comment by ibananas** [comment]
非常感谢大佬的开源😊
