### ISSUE TITLE
能不能出个发布图文笔记的接口啊 万分感谢

### ISSUE THREAD

**Issue by kevinsir** [ReaJason/xhs#20]
能不能出个发布图文笔记的接口啊 万分感谢

**Comment by ReaJason** [comment]
> 能不能出个发布图文笔记的接口啊 万分感谢

有时间可能会研究一下（现在一直没时间），目标网站是这个 👉 https://creator.xiaohongshu.com

**Comment by kevinsir** [comment]
好的，感谢

**Comment by SnailDev** [comment]
能不能出个发布图文笔记的接口啊 万分感谢

**Comment by ReaJason** [comment]
好消息，现在两个网站可以共用一个 cookie 因此，能减缓开发进度，不过签名参数仍然是一个大问题

**Comment by ReaJason** [comment]
resolved #26, please upgrade v0.2.4

simple usage:
https://github.com/ReaJason/xhs/blob/fc1ee650c3a58bf95de42e0652e84e1631e34ddf/tests/test_xhs.py#L312
