### ISSUE TITLE
sign函数里面的uri是什么参数啊

### ISSUE THREAD

**Issue by LumingMelody** [ReaJason/xhs#24]

**Comment by ReaJason** [comment]
<img width="574" alt="image" src="https://github.com/ReaJason/xhs/assets/48389642/da584aa0-32a7-457f-a6d8-e31e00170e88">

**Comment by LumingMelody** [comment]
> <img alt="image" width="574" src="https://user-images.githubusercontent.com/48389642/249080249-da584aa0-32a7-457f-a6d8-e31e00170e88.png">

这个py文件在哪 没看到啊

**Comment by ReaJason** [comment]
> 这个py文件在哪 没看到啊

https://github.com/ReaJason/xhs/blob/3531ec90903aaac917cdcd70cd056c62defa2850/xhs/core.py#L558

**Comment by LumingMelody** [comment]
> > 这个py文件在哪 没看到啊
> 
> https://github.com/ReaJason/xhs/blob/3531ec90903aaac917cdcd70cd056c62defa2850/xhs/core.py#L558
cookie 是把web完整的cookie复制过去吗 我全部复制过去报错了

**Comment by ReaJason** [comment]
需要把每个cookie key 前的空格去掉，我忘记加 trim 了，晚点加一下
