### ISSUE TITLE
is_creator的作用是什么？

### ISSUE THREAD

**Issue by Esword618** [ReaJason/xhs#27]
is_creator的作用是什么，我看都是默认的false，好像没有用过true

**Comment by ReaJason** [comment]
给这个网站用的，https://creator.xiaohongshu.com，写了一点这个网站的 API，不过两个签名好像能通用，所以暂时没用到了

**Comment by Esword618** [comment]
哦哦，那我就先不加入了，我把这个python版的改写go版了，所以问一您，大佬太强了

**Comment by ReaJason** [comment]
> 哦哦，那我就先不加入了，我把这个python版的改写go版了，所以问一您，大佬太强了

可以，这个项目就是简单的抽取 API 并没有能被称为大佬的地步哈，谢谢认可🌹
