### ISSUE TITLE
sign函数问题

### ISSUE THREAD

**Issue by xiaojue** [ReaJason/xhs#28]
现在内置的sign函数算出来的x-s长度和web网站的长度不一致，请求的时候一直返回 {'code': -1, 'success': False} 

请问作者现在还维护吗？

**Comment by xiaojue** [comment]
我根据readme里和官方文档的用法都无法使用  get_user_notes 方法获取数据

**Comment by ReaJason** [comment]
> 我根据readme里和官方文档的用法都无法使用 get_user_notes 方法获取数据

请问没有报错截图，啥的信息，怎么帮助你？

**Comment by ReaJason** [comment]
测试了 README 的使用方式还是可行的，关于 sign 函数目前已不可用了。

<img width="871" alt="image" src="https://github.com/ReaJason/xhs/assets/48389642/47654663-e3f2-40bf-86ff-53b60395389b">
