### ISSUE TITLE
初始化client后，调用get_user_notes方法提示无登录信息，或登录信息为空

### ISSUE THREAD

**Issue by ianho7** [ReaJason/xhs#3]
按照[文档](https://reajason.github.io/xhs/)执行如下代码，提示“无登录信息，或登录信息为空”
```
from xhs import XhsClient

// cookie在网页https://www.xiaohongshu.com/user/profile/用户ID 
// 执行js代码：console.log(document.cookie); 得到，

cookie = "请从网页端获取你的 cookie" 
xhs_client = XhsClient(cookie)


result = xhs_client.get_user_notes("用户ID")
print(result)
```

执行效果如图：

![image](https://user-images.githubusercontent.com/26101033/231941328-c7a829c7-fd16-421b-931c-7e307bc047b5.png)

请问如何能正常使用，谢谢🙏

**Comment by ReaJason** [comment]
你去浏览器登录小红书，然后把 cookie 放到代码的 cookie 那个地方

**Comment by ReaJason** [comment]
麻烦去请求里面拿 cookie，我刚试了 document.cookie 是拿不到登录的那个 sessionId 的。

![image](https://user-images.githubusercontent.com/48389642/231958242-1968e155-a670-44d2-859c-fcf77cbfdf1a.png)

**Comment by ianho7** [comment]
> 麻烦去请求里面拿 cookie，我刚试了 document.cookie 是拿不到登录的那个 sessionId 的。
> 
> ![image](https://user-images.githubusercontent.com/48389642/231958242-1968e155-a670-44d2-859c-fcf77cbfdf1a.png)

可以了，感谢！

**Comment by ianho7** [comment]
@ReaJason 对了，请问目前有方法可以获取到笔记的浏览量/阅读数吗？

**Comment by ReaJason** [comment]
> @ReaJason 对了，请问目前有方法可以获取到笔记的浏览量/阅读数吗？

[小红书创作服务平台](https://creator.xiaohongshu.com/publish/) 这个上面能获取自己的，别人的没办法

**Comment by ianho7** [comment]
> > @ReaJason 对了，请问目前有方法可以获取到笔记的浏览量/阅读数吗？
> 
> [小红书创作服务平台](https://creator.xiaohongshu.com/publish/) 这个上面能获取自己的，别人的没办法

好的，谢谢

**Comment by MoncozGC** [comment]
> 麻烦去请求里面拿 cookie，我刚试了 document.cookie 是拿不到登录的那个 sessionId 的。
> 
> ![image](https://user-images.githubusercontent.com/48389642/231958242-1968e155-a670-44d2-859c-fcf77cbfdf1a.png)

请问一下，我是根据这个接口获取的cookie，但是在请求的时候会报错。
可以指导下嘛

代码:
```python
xhs_client = XhsClient(cookie)

# 获取笔记内容
text = xhs_client.get_note_by_id("643b522c00000000130331c5")
print(text)
```
cookie截图
![image](https://user-images.githubusercontent.com/35448093/233112107-97678b8a-4b3e-42c4-b596-4e20dc5850ae.png)

报错信息:
requests.exceptions.SSLError: HTTPSConnectionPool(host='edith.xiaohongshu.com', port=443): Max retries exceeded with url: /api/sns/web/v1/feed (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))

**Comment by ReaJason** [comment]
> 请问一下，我是根据这个接口获取的cookie，但是在请求的时候会报错。 可以指导下嘛
> 
> 代码:
> 
> ```python
> xhs_client = XhsClient(cookie)
> 
> # 获取笔记内容
> text = xhs_client.get_note_by_id("643b522c00000000130331c5")
> print(text)
> ```
> 
> cookie截图 ![image](https://user-images.githubusercontent.com/35448093/233112107-97678b8a-4b3e-42c4-b596-4e20dc5850ae.png)
> 
> 报错信息: requests.exceptions.SSLError: HTTPSConnectionPool(host='edith.xiaohongshu.com', port=443): Max retries exceeded with url: /api/sns/web/v1/feed (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))

你这种情况应该是网络问题，请尝试直接访问网页端看能否访问，或者电脑代理，把代理给关掉

**Comment by MoncozGC** [comment]
> 
> 你这种情况应该是网络问题，请尝试直接访问网页端看能否访问，或者电脑代理，把代理给关掉

确实是代理的问题，关闭代理就好了，不知道为什么网页端可以访问但是执行代码就会报错。
感谢~
