### ISSUE TITLE
请问get_user_all_notes函数可以设置爬取笔记个数吗

### ISSUE THREAD

**Issue by Nomination-NRB** [ReaJason/xhs#34]
如题
情况：当一个博主笔记量太多了，有几百个，但是只有最新的几十个比较有用，是否可以**设置限制**爬取的笔记**个数**呢

**Comment by ReaJason** [comment]
可以参考这个接口实现，自己实现相关功能，这个接口只是用来给一个例子的，暂没有在此基础上做其他自定义操作的想法

**Comment by Nomination-NRB** [comment]
好的，感谢回复
