### ISSUE TITLE
更新之后一直显示“xhs.exception.DataFetchError: {'code': -1, 'success': False}”

### ISSUE THREAD

**Issue by tangtr** [ReaJason/xhs#35]
之前有时会显示“当前内容无法展示”，昨天更新了一下一直报错：
  auth_info = xhs_client.get_user_info(line)
  File "C:\python\lib\site-packages\xhs\core.py", line 315, in get_user_info
    return self.get(uri, params)
  File "C:\python\lib\site-packages\xhs\core.py", line 173, in get
    return self.request(method="GET", url=f"{self._host}{final_uri}")
  File "C:\python\lib\site-packages\xhs\core.py", line 165, in request
    raise DataFetchError(data.get("msg", data))
xhs.exception.DataFetchError: {'code': -1, 'success': False}

请帮助

**Comment by ReaJason** [comment]
请问使用的 Docker 容器吗，签名好像坏了，我有时间修修，本地起的还是好使的
<img width="972" alt="image" src="https://github.com/ReaJason/xhs/assets/48389642/cfd442b0-ec10-4462-8fd2-812957a281a7">

**Comment by tangtr** [comment]
> 请问使用的 Docker 容器吗，签名好像坏了，我有时间修修，本地起的还是好使的 <img alt="image" width="972" src="https://user-images.githubusercontent.com/48389642/255788890-cfd442b0-ec10-4462-8fd2-812957a281a7.png">

哦，我也是使用本地签名，不是docker，不知道哪里出了状况。我再试试。

**Comment by ReaJason** [comment]
basic_usage.py 能用，那个 flask server 不行了

**Comment by tangtr** [comment]
> basic_usage.py 能用，那个 flask server 不行了

好滴
