### ISSUE TITLE
PySide6 用户界面开发

### ISSUE THREAD

**Issue by ReaJason** [ReaJason/xhs#4]
- [ ] 支持 cookie 登录、短信登录以及二维码登录
- [ ] 支持指定笔记爬取笔记内容以及用户评论
- [x] 支持支持爬取用户所有笔记详情
- [ ] 支持笔记评论自动回复
- [ ] 博主笔记更新提醒
- [ ] 根据关键字爬取笔记详情

**Comment by Aaronchenn** [comment]
谢谢大佬

**Comment by ReaJason** [comment]
> 谢谢大佬

hhhh，客气了，你们的反馈就是对我最大的鼓励🌹

**Comment by ZhangTongXiang** [comment]
棒极了 大赞
