### ISSUE TITLE
get_user_notes无法获取所有的用户笔记

### ISSUE THREAD

**Issue by iray1024** [ReaJason/xhs#42]
用 “xhs_client.get_user_notes("用户ID")” 这个api获取用户笔记时，无法获取全

返回的json数据包含了当前游标cursor和has_more来确认是否还有更多笔记以及请求更多笔记数量的偏移量，

但是您并没有提供处理笔记游标cursor的api

![image](https://github.com/ReaJason/xhs/assets/49387318/c52b2d78-40b5-430f-a7d1-831c9c671cae)

**Comment by ReaJason** [comment]
get_user_notes("用户id", "游标id")，这个函数的第二参数就是哦，具体用户可以参考下一个函数的实现
https://github.com/ReaJason/xhs/blob/883392f290c992fd71f304d693e53f798e0253f0/xhs/core.py#L409
![image](https://github.com/ReaJason/xhs/assets/48389642/06ea0f65-f9d3-4ebd-8254-df8bf66c1a73)

**Comment by iray1024** [comment]
欧克欧克，我看文档上还以为只有一个参数。。。

![image](https://github.com/ReaJason/xhs/assets/49387318/d4d8e6d4-b4ca-4f59-b9b3-8d387e185b96)
