### ISSUE TITLE
basic_usage does not work as of 08/25/23

### ISSUE THREAD

**Issue by mendyl-nb** [ReaJason/xhs#43]
I used to be able to run basic_usage.py. But since yesterday, it does not work anymore. and I get 
`xhs.exception.DataFetchError: {'code': -1, 'success': False}`
不确定是不是小红书那侧做了一些修改导致xhs不可用了

**Comment by ReaJason** [comment]
请尝试用新的 base_usage.py，加了失败重试

**Comment by mendyl-nb** [comment]
感谢回复！不过我这边重试了十次都还是不行 @ReaJason 你run的时候是重试就可以成功的 是吗

**Comment by ReaJason** [comment]
我这边重试能成功，你可以设置 headless 为 False 来打开浏览器测试，请问你具体重试失败的地方在哪儿

**Comment by mendyl-nb** [comment]
好的 感谢！ @ReaJason 
测试发现一个是网页加载特别慢，另外卡在了滑块那边，看了另一个issue，cookie里加了webId之后就可以了
