### ISSUE TITLE
部分笔记在web端会出现-510001，"当前内容无法展示"，但是实际在app端可以查看，这种情况可以获取吗？

### ISSUE THREAD

**Issue by FairyWorld** [ReaJason/xhs#44]
部分笔记在web端会出现-510001，"当前内容无法展示"，但是实际在app端可以查看，这种情况可以获取吗？

**Comment by ReaJason** [comment]
这种情况暂时没有解决办法，web 端接口确实不太好使，你这只能想办法弄 app 的接口了，我还不太会。
