### ISSUE TITLE
获取笔记评论只能拿到前10个

### ISSUE THREAD

**Issue by wuwen6937** [ReaJason/xhs#45]
我试了几个不同的笔记好像都是这样，请问别人有同样的问题吗？

**Comment by ReaJason** [comment]
请使用或参考获取笔记所有评论接口

https://github.com/ReaJason/xhs/blob/f2e11685d4cf00d3fd4e2bdd5af1133cd2d17c57/xhs/core.py#L495

**Comment by wuwen6937** [comment]
谢谢！我试了一下 好像超过5000个评论就会要求验证，请问有什么方法吗

**Comment by ReaJason** [comment]
请问是旋转验证码吗，不好意思目前我这还没解决方案
