### ISSUE TITLE
小红书发布笔记问题

### ISSUE THREAD

**Issue by submato** [ReaJason/xhs#48]
小红书发布笔记出现报错：TypeError: window._webmsxyw is not a function。
在https://creator.xiaohongshu.com/ 的控制台中输入console.log(window._webmsxyw)，结果确实是undefined
同样的代码在https://www.xiaohongshu.com/的控制台中能够获取到方法

**Comment by ReaJason** [comment]
麻烦贴一下你的完整代码

**Comment by submato** [comment]
<img width="992" alt="image" src="https://github.com/ReaJason/xhs/assets/55040284/5f842f74-a098-4cab-8976-e08e06dbe3c1">
<img width="984" alt="image" src="https://github.com/ReaJason/xhs/assets/55040284/8d3fa1a1-82bc-4b08-bc85-f082462e0b1d">
没有其他地方改动

**Comment by submato** [comment]
import datetime
import json
import time
from time import sleep
from xhs import XhsClient, DataFetchError
from playwright.sync_api import sync_playwright


def sign(uri, data=None, a1="", web_session=""):
    a1 = "184d1885b79kueq8zufxxah0brzchxbn06l7mjxbt00000242961"
    web_session = "030037a4bacfca1df4c843818d234a7ff0320a"
    for _ in range(10):
        try:
            with sync_playwright() as playwright:
                stealth_js_path = "/Users/bilibili/xhs/stealth.min.js"
                chromium = playwright.chromium

                # 如果一直失败可尝试设置成 False 让其打开浏览器，适当添加 sleep 可查看浏览器状态
                browser = chromium.launch(headless=True)

                browser_context = browser.new_context()
                browser_context.add_init_script(path=stealth_js_path)
                context_page = browser_context.new_page()


                context_page.goto("https://creator.xiaohongshu.com/")
                browser_context.add_cookies([
                    {'name': 'web_session', 'value': web_session, 'domain': ".xiaohongshu.com", 'path': "/"},
                    {'name': 'a1', 'value': a1, 'domain': ".xiaohongshu.com", 'path': "/"}]
                )
                print(browser_context.cookies())

                # 这个地方设置完浏览器 cookie 之后，如果这儿不 sleep 一下签名获取就失败了，如果经常失败请设置长一点试试
                sleep(5)
                context_page.wait_for_load_state('load')
                encrypt_params = context_page.evaluate("([url, data]) => window._webmsxyw(url, data)", [uri, data])
                print({
                    "x-s": encrypt_params["X-s"],
                    "x-t": str(encrypt_params["X-t"])
                })
                return {
                    "x-s": encrypt_params["X-s"],
                    "x-t": str(encrypt_params["X-t"])
                }
        except Exception as e:
            # 这儿有时会出现 window._webmsxyw is not a function 或未知跳转错误，因此加一个失败重试趴
            print(e)
    raise Exception("重试了这么多次还是无法签名成功，寄寄寄")


if __name__ == '__main__':
    cookie = ""
    xhs_client = XhsClient(cookie, sign=sign)
    print(datetime.datetime.now())

    title = "新人求关"
    desc = "新人求关"
    images = [
        "/Users/Desktop/WechatIMG34957.png",
    ]

    for _ in range(3):
        # 即便上面做了重试，还是有可能会遇到签名失败的情况，重试即可
        try:
            note = xhs_client.create_image_note(title, desc, images, is_private=True, post_time=datetime.datetime.now())
            break
        except DataFetchError as e:
            print("失败重试一下下")

**Comment by submato** [comment]
fixed
