### ISSUE TITLE
请问，有没有办法获取关注的人数呢。

### ISSUE THREAD

**Issue by cosylxc** [ReaJason/xhs#49]
我想把我关注的都爬了，但一个个分享到电脑我要死的，大概500个，大佬有没有办法破解一下，我知道我是强人锁男，就问一下😭主要我硬盘炸了，又没有备份，之前都是一个个分享到桌面端。太惨了😭

**Comment by ReaJason** [comment]
Web 端目前只有获取关注人数，而没有获取具体关注列表的接口，或许你可以抓取你点赞的笔记，然后小红书 id 去重呢，猜测点赞的其中应该有很多关注的吧。

**Comment by cshwill** [comment]
App 上可以获取
接上抓包工具，在 App 上把所有关注都 load 出来，关注的人的信息就都出来了

必须是 iOS 版本，以及如果是 macOS，推荐使用 mitmproxy

**Comment by cosylxc** [comment]
@cshwill 非常感谢，抓包一下就获得了，一下子节约了好多时间。😄😄让我又想起了以前一个个视频手动下载的脑瓜时候😂
