### ISSUE TITLE
traceId 现在为空了，还有其他方法能获取无水印的链接吗

### ISSUE THREAD

**Issue by zhouzhili** [ReaJason/xhs#50]
![image](https://github.com/ReaJason/xhs/assets/14259932/265d4354-6461-4d3c-bd17-9e3e80beeee6)

**Comment by cosylxc** [comment]
图片链接中间的那一段好像就是原来的traceid，你要截取一下，然后视频的key好在，

**Comment by zhouzhili** [comment]
> 图片链接中间的那一段好像就是原来的traceid，你要截取一下，然后视频的key好在，

大佬，可否详细说说

**Comment by cosylxc** [comment]
@zhouzhili 你看网页源码，不是有图片链接吗，封面再加上点开后的图，它们链接中有一串1040g…这样的字符串，好像就是原来的traid，我下载了一下，图片尺寸大小什么的都正常。

**Comment by Jeffrey-deng** [comment]
> @zhouzhili 你看网页源码，不是有图片链接吗，封面再加上点开后的图，它们链接中有一串1040g…这样的字符串，好像就是原来的traid，我下载了一下，图片尺寸大小什么的都正常。

没找到哎，能否截下图

**Comment by cosylxc** [comment]
@Jeffrey-deng ![image](https://github.com/ReaJason/xhs/assets/88622185/dd91c042-8097-4a54-a6f4-4506f48dc0f0)

**Comment by Jeffrey-deng** [comment]
> @Jeffrey-deng ![image](https://user-images.githubusercontent.com/88622185/268439035-dd91c042-8097-4a54-a6f4-4506f48dc0f0.jpeg)

嗯嗯，在下面的js对象里也有
我是这样处理的

```
imageList = note_info['image_list']
for image in imageList:
    if image['trace_id'] is not None and image['trace_id'] != '':
        image_file_urls.append('https://sns-img-bd.xhscdn.com/%s' % image['trace_id'])
        image_file_ids.append(image['trace_id'])
    else:
        image_file_url = list(filter(lambda info: info['image_scene'] == 'CRD_WM_WEBP', image['info_list']))[0]['url']
        image_file_urls.append(image_file_url)
```
