### ISSUE TITLE
2023-09-20 get_note_by_id这个功能不生效了

### ISSUE THREAD

**Issue by gyco** [ReaJason/xhs#53]
通过cookie获取笔记详情的功能失效了 大佬辛苦修复下!

**Comment by ReaJason** [comment]
嗯呢，似乎所有接口的签名都错误了，有时间看一下

**Comment by jqsl2012** [comment]
@ReaJason 大佬，我这边也失败了
报错信息：
playwright._impl._api_types.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
2023-09-20 07:20:27.249129

**Comment by jqsl2012** [comment]
@ReaJason 大佬，能不能加急修复一下，我给你推广你的项目

**Comment by gyco** [comment]
https://bbs.kanxue.com/thread-278934.htm  贴个找到的资源 不知道是否适用 @ReaJason

**Comment by ReaJason** [comment]
急需的朋友可自行修改 sign 函数即可

**Comment by gyco** [comment]
这个sign函数 需要改 哪里?

**Comment by gyco** [comment]
大佬 这个sign函数 需要怎么改?

**Comment by ReaJason** [comment]
参考 cc5dfc061b9511fbaf04b4e1377adaa51e3b0cc9
