### ISSUE TITLE
请问大佬有没有方法能拿到笔记详情页的原图

### ISSUE THREAD

**Issue by MH-188** [ReaJason/xhs#55]
![image](https://github.com/ReaJason/xhs/assets/64905947/72810aa8-cac8-45c0-b96a-293821651709)
我试过替换这个参数，可以获取到jpg格式的图，但是就拿不到原图了

**Comment by ReaJason** [comment]
可以呀，参考 [basic_usage.py](https://github.com/ReaJason/xhs/blob/master/example/basic_usage.py)
![CleanShot 2023-09-21 at 12 51 16@2x](https://github.com/ReaJason/xhs/assets/48389642/0d7b4ef2-4318-4cde-8a9b-a0865bf54e6d)

**Comment by MH-188** [comment]
看到了，原来的id藏在这里，谢谢！！
