### ISSUE TITLE
评论笔记接口@功能

### ISSUE THREAD

**Issue by godJBJ** [ReaJason/xhs#57]
所遇到的问题：
    评论笔记接口，当我想@别人的时候，我输入“@小红薯”，可以正常发布该评论，但是@别人的功能并没有体现出来，也就是说他收不到我的@。

进行的尝试：
    给评论笔记接口传入“at_users”参数，但发现仍不生效
![image](https://github.com/ReaJason/xhs/assets/64889128/b2f7af65-a614-480c-b3c6-74f6fd1f5039)
![image](https://github.com/ReaJason/xhs/assets/64889128/87af1c62-c443-4119-9d33-b7b241ce06c6)

还请大佬赐教，十分感谢！

**Comment by ReaJason** [comment]
麻烦参考这个测试用例进行修改调整：

https://github.com/ReaJason/xhs/blob/5b3df45ce7fa127d1c09f1404c70ced0dc5bd4b4/tests/test_xhs.py#L319

**Comment by godJBJ** [comment]
谢谢！！已能正常@

**Comment by qiushui123** [comment]
> 谢谢！！已能正常@

可以截图看一下你的代码吗，我能@成功，但是别人收不到消息

**Comment by lucasjinreal** [comment]
我想检测我的账号被@，咋弄啊
