### ISSUE TITLE
请问basic_usage.py中如何进行分页搜索获取结果

### ISSUE THREAD

**Issue by jqsl2012** [ReaJason/xhs#59]
我有一个需求就是需要根据关键词列表进行分页搜索，但是basic_usage.py中没看到哪里指定分页数，请问这种情况该如何处理i呢

**Comment by ReaJason** [comment]
https://github.com/ReaJason/xhs/blob/fa41e3b03ebd4a48eb3bb6bed17c1209e8276cd0/xhs/core.py#L367

**Comment by jqsl2012** [comment]
好的谢谢
