### ISSUE TITLE
关注用户，用户好像不能收到通知

### ISSUE THREAD

**Issue by godJBJ** [ReaJason/xhs#71]
作者您好！
测试使用关注用户接口，能达到关注的效果，但是用户好像收不到通知？
我使用网页版测试，网页上关注是正常的可以收到通知的，请教一下你那边关注接口是正常的吗？
谢谢！

**Comment by ReaJason** [comment]
关注别人，能成功关注不就可以吧，为什么一定要别人收到通知，请问这个具体需求是什么？有可能这个接口做了风控
