### ISSUE TITLE
如何监控被用户评论区@的消息

### ISSUE THREAD

**Issue by lucasjinreal** [ReaJason/xhs#72]
又办法可以做到吗

**Comment by ReaJason** [comment]
请问你说的是这儿的接口吗，我看这个应该是最近才开放的吧，可能得加一下

![CleanShot 2023-11-07 at 20 52 27@2x](https://github.com/ReaJason/xhs/assets/48389642/5d54e0c2-15fe-4c90-b698-a4c3f7bec076)

**Comment by lucasjinreal** [comment]
@FairyWorld  是的，不过不太确定如何做成回调的形式，可能得类似于轮询？然后给用户提供一个触发接口

@FairyWorld 我的需求不是搜索文本，就是别人艾特了我，我要收到回调

**Comment by xRuanle** [comment]
> @FairyWorld 是的，不过不太确定如何做成回调的形式，可能得类似于轮询？然后给用户提供一个触发接口
> 
> @FairyWorld 我的需求不是搜索文本，就是别人艾特了我，我要收到回调

回调不太可能，只能轮询。我现在有一个需求和你的类似，就是我的笔记评论区被评论，我这边检测到关键字后自动进行回复。用的是rabbitmq

**Comment by lucasjinreal** [comment]
@xRuanle  用的是xhs吗？ 这个楼主可以考虑支持一下，如何一旦可以轮询检测，就可以实现任意帖子回复

**Comment by ReaJason** [comment]
```
mention_notifications = xhs_client.get_mention_notifications()

like_notifications = xhs_client.get_like_notifications()

follow_notifications = xhs_client.get_follow_notifications()
```

**Comment by lucasjinreal** [comment]
@ReaJason  感谢楼主，但你这个是鸡生蛋诞生记自己嵌套了。

我想要的是别人mention了触发，当我 get_mention的前提是我知道啥时候get。如果可以for 循环轮询，是否可以考虑直接封装个callback接口给用户使用。
