### ISSUE TITLE
使用求助

### ISSUE THREAD

**Issue by theodore-abbott** [ReaJason/xhs#8]
感谢大佬开发的工具，使用时遇到了一个小问题，当获取博主所有笔记时，软件获取列表会获取一部分，然后下载时会下载列表内的一部分，例如共100篇，获取时获取了70，下载时下载了50。不知道是不是共性问题，希望大佬有时间可以查看一下，附博主号“5b13f01511be104e943a48ba”、或“5a6ec20cb1da1434c660a82d”

**Comment by ReaJason** [comment]
这个笔记过多导致被封掉了，后续可能会加一个请求间隔的设置然后看哪个间隔更合理

**Comment by bxaiqiyi** [comment]
大佬你现在不更新了吗？哪里有更细那文件可以下载呢？找不到，或者你能整个群之类的吗？

**Comment by ReaJason** [comment]
> 大佬你现在不更新了吗？哪里有更细那文件可以下载呢？找不到，或者你能整个群之类的吗？

https://lingsiki.lanzouw.com/b0en2jwzg
密码:cih8

**Comment by theodore-abbott** [comment]
> 这个笔记过多导致被封掉了，后续可能会加一个请求间隔的设置然后看哪个间隔更合理

好哒，感谢大佬

**Comment by bxaiqiyi** [comment]
获取博主笔记错误
[网络连接异常]
将暂停三分钟后继续爬取...

一直提示这个，不知道杂回事呢？
大佬能弄个群来沟通吗？

**Comment by bxaiqiyi** [comment]
可以加一个博主信息的资讯吗？比如当前博主有多少篇笔记。视频多少，文章多少。下载的数据中，能不能把点赞收藏的数量和数据留下

**Comment by ReaJason** [comment]
> 获取博主笔记错误 [网络连接异常] 将暂停三分钟后继续爬取...
> 
> 一直提示这个，不知道杂回事呢？ 大佬能弄个群来沟通吗？

程序的关于那一页有 Q 群

**Comment by ReaJason** [comment]
> 可以加一个博主信息的资讯吗？比如当前博主有多少篇笔记。视频多少，文章多少。下载的数据中，能不能把点赞收藏的数量和数据留下

下载的数据有所有的信息，你可以看那个 json 后缀的文件
