### ISSUE TITLE
下载笔记时，图片下载失败

### ISSUE THREAD

**Issue by GaoHaHa-IronMan** [ReaJason/xhs#80]
python版本：3.11
xhs版本：0.2.7
源码：
if __name__ == '__main__':
    xhs_client.save_files_from_note_id("64dc3e60000000000103fba4", "/PycharmProjects/pythonProject/download")

错误：
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://sns-img-qn.xhscdn.com/1040g0k030nqoqi15gm005omefsa5b5vgnn9pi7g?imageView2/format/png

**Comment by ReaJason** [comment]
感谢反馈，可能是无水印图片解析算法有问题了有时间我看看

**Comment by GaoHaHa-IronMan** [comment]
> v0.2.9 修复了这个问题，麻烦更新一下，再次感谢反馈💐
> 
> ```shell
> pip install xhs==0.2.9
> ```

我试0.2.9还是无法下载，0.2.8可以成功下载。
