### ISSUE TITLE
get_user_info  get_user_notes  get_note_by_id 这几个貌似失效了

### ISSUE THREAD

**Issue by yslion** [ReaJason/xhs#81]
![image](https://github.com/ReaJason/xhs/assets/4454836/28d67321-fa6d-4c56-a3bf-fe1d3b620e7c)

cookie填写后
get_self_info  get_home_feed(xhs.FeedType.RECOMMEND)  这几个能正常打印  
follow_user(user_id) 这个也可以
截图里的 get_user_info  get_user_notes  get_note_by_id  这三个 都不行

**Comment by ReaJason** [comment]
我这儿测试目前是没问题，你那儿返回的空数据，我猜测是和 cookie 有关，可以尝试换一个 cookie 试试。

![CleanShot 2024-01-30 at 08 56 11@2x](https://github.com/ReaJason/xhs/assets/48389642/282ec912-23e5-4183-b2c0-06134a40f487)

**Comment by ReaJason** [comment]
461 这个响应头里面有没有包含 verify 相关的字眼，目前写了一个 471 的响应码是被验证码给拦截了，我猜测 461 可能类似的

https://github.com/ReaJason/xhs/blob/34a0ea3aeba2faa20d8a5b986b98dc1093b2d266/xhs/core.py#L170-L174

**Comment by glorysaladin** [comment]
> 461 这个响应头里面有没有包含 verify 相关的字眼，目前写了一个 471 的响应码是被验证码给拦截了，我猜测 461 可能类似的
> 
> https://github.com/ReaJason/xhs/blob/34a0ea3aeba2faa20d8a5b986b98dc1093b2d266/xhs/core.py#L170-L174

验证码拦截这种有办法解答吗？ 目前调用get_note_by_id的接口会返回 461； 三个账号使用的同一个签名服务器，同一个a1; 有两个返回461， 一个正常
