### ISSUE TITLE
图文话题 上传失败

### ISSUE THREAD

**Issue by SarcomTDG** [ReaJason/xhs#82]
话题上传返回了，但是xhs_client.create_video_note进行调用传话题返回的list，在小红书上面不显示

**Comment by ReaJason** [comment]
https://www.xiaohongshu.com/explore/65b8eef3000000002b03dceb

可以的呀，请问可以给一下报错信息不

![CleanShot 2024-01-30 at 20 44 08@2x](https://github.com/ReaJason/xhs/assets/48389642/db05e459-0892-4caa-9389-f200fc58c43c)

**Comment by SarcomTDG** [comment]
没有报错，话题上传没问题，但是小红书上面无相关话题显示
![微信截图_20240131215529](https://github.com/ReaJason/xhs/assets/95288331/7b582bf2-0ca1-4b08-9964-9883d7791a56)
![微信截图_20240131215453](https://github.com/ReaJason/xhs/assets/95288331/5925d58c-dd0a-4575-9c10-2854b8191d08)
![微信图片_20240131215714](https://github.com/ReaJason/xhs/assets/95288331/083b03a3-38c3-416e-bf6a-018f6c602f7f)

**Comment by ReaJason** [comment]
请参考如下示例

```python
def test_create_note_with_ats_topics(xhs_client: XhsClient):
    title = "我是通过自动发布脚本发送的笔记"
    desc = "deployed by GitHub xhs， #Python[话题]# @ReaJason"
    files = [
        "/Users/reajason/Downloads/wall/wallhaven-x6k21l.png",
    ]

    # 可以通过 xhs_client.get_suggest_ats(ats_keyword) 接口获取用户数据
    ats = [
        {"nickname": "ReaJason", "user_id": "63273a77000000002303cc9b", "name": "ReaJason"}
    ]

    # 可以通过 xhs_client.get_suggest_topic(topic_keyword) 接口获取标签数据
    topics = [
        {
            "id": "5d35dd9b000000000e0088dc", "name": "Python", "type": "topic",
            "link": "https://www.xiaohongshu.com/page/topics/5d35dd9ba059940001703e38?naviHidden=yes"
        }
    ]
    note = xhs_client.create_image_note(title, desc, files, ats=ats, topics=topics, is_private=True,
                                        post_time="2023-07-25 23:59:59")
    beauty_print(note)
```
