### ISSUE TITLE
关于代理和sign

### ISSUE THREAD

**Issue by yslion** [ReaJason/xhs#83]
带佬，请教个问题： 假设我有10个账号，5个代理ip。  我用的 sign方法是basic_sign_server里的 。 这个代理怎么挂比较合理？ 是 起1个不挂代理的basic_sign_server ， 初始化client的时候，不同账号对应一下代理ip就可以 ，还是 起5个 basic_sign_server，每个挂一个代理，再根据代理初始化client  。

简而言之，就是 签名和具体初始化以及api操作，要不要必须都在同一个代理ip下进行

**Comment by ReaJason** [comment]
签名服务和 client 不需要在同一个代理 ip 下，如果签名能正常签名就基本不会有太多问题，给 client 挂代理 ip 就可
