### ISSUE TITLE
用手机验证码登录，执行login_phone.py报错，请问是什么原因

### ISSUE THREAD

**Issue by DavinBin** [ReaJason/xhs#84]
能拿到mobile_token

![image](https://github.com/ReaJason/xhs/assets/20571035/06e55581-948b-4594-b6b4-9a91030c738c)

**Comment by ReaJason** [comment]
emmm，我的本地环境被验证码挡了，测不了这个情况，暂时还没找到解决办法

**Comment by ReaJason** [comment]
目前应该没有这个问题，我这边走通了，如果报需要验证码，目前也没有办法
