### ISSUE TITLE
扫码登录时遇到httpcode 471

### ISSUE THREAD

**Issue by submato** [ReaJason/xhs#86]
问题：在运行login_qrcode.py时，在app扫码之后，check_qrcode()函数，返回值为{'code': 0, 'success': True, 'msg': 'true', 'data': {}}；其httpcode为471。 

目前发现这个是有些账号会出现的，但是有时候又会返回正常。

想请问作者是否遇到过类似情况，如何解决。

**Comment by ReaJason** [comment]
471 是被验证码给挡了，目前还没解决办法
