### ISSUE TITLE
发送短信出现错误

### ISSUE THREAD

**Issue by beiming-org** [ReaJason/xhs#96]
![image](https://github.com/ReaJason/xhs/assets/81206614/a7bf4b77-7326-4d69-88de-51418f97f58f)

**Comment by beiming-org** [comment]
![image](https://github.com/ReaJason/xhs/assets/81206614/4d736a10-5f46-4fdf-ba3f-6fcc967da764)
发布帖子，最后一步卡主了

**Comment by beiming-org** [comment]
![image](https://github.com/ReaJason/xhs/assets/81206614/7311a158-d3e0-4fcd-81bb-5d04d2aae7fb)
提示，无登录信息

**Comment by ReaJason** [comment]
> ![image](https://private-user-images.githubusercontent.com/81206614/321985705-7311a158-d3e0-4fcd-81bb-5d04d2aae7fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5ODExNDEsIm5iZiI6MTcxMjk4MDg0MSwicGF0aCI6Ii84MTIwNjYxNC8zMjE5ODU3MDUtNzMxMWExNTgtZDNlMC00ZmNkLTgxYmItNWQwNGQyYWFlN2ZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDA0MDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMDE0ZTYyNDNkNTYzZTg0ZmFlYTNjODFkZGZkNzEzMTRjM2Q3ODcwNGQ3ZmQ1YmFhNTQ5OGZlYjI5ODM5ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Iki4727Dtc5L9UHLBm_PUfarXEyyn-Ik8STB75rowhc) 提示，无登录信息

参考这个 #66

**Comment by beiming-org** [comment]
@ReaJason 您好，我现在获取到的返回信息是验证码发送成功，但是我没有收到验证码，我自己两个号码都是一样的情况
![image](https://github.com/ReaJason/xhs/assets/81206614/9a2cccb9-c412-46fa-8484-255b701c72b0)
