### ISSUE TITLE
在mac，m1上，不行🙅 

### ISSUE THREAD

**Issue by MrHe007** [ReaJason/xhs#97]
Exception: 重试了这么多次还是无法签名成功，寄寄寄

**Comment by ReaJason** [comment]
https://github.com/ReaJason/xhs/blob/34a0ea3aeba2faa20d8a5b986b98dc1093b2d266/example/basic_usage.py#L17

**Comment by MrHe007** [comment]
抱歉，是mac也是可以的。昨天我弄好了。是我没下载好PlayWright的驱动
