### ISSUE TITLE
获取笔记信息的时候报错

### ISSUE THREAD

**Issue by baixing99** [ReaJason/xhs#99]
获取笔记信息的时候报错
代码如下
xhs_client.get_note_by_id('661c8fea000000001a017c58')
错误信息如下
![ca80ca10c8f0fb7c8b4a9ff2a1421a4](https://github.com/ReaJason/xhs/assets/73473087/3fdbe4e7-55eb-4dd6-8de0-1b7becdf690d)
![1eb005be72bea2a8522e2879a5a8ea1](https://github.com/ReaJason/xhs/assets/73473087/051ca037-3176-4e1b-b9e5-e5f220ed6a32)
![b6b3792ac9acc7b5e083334ab3f2a03](https://github.com/ReaJason/xhs/assets/73473087/66cd485b-923d-4824-80f0-45bdc2701bff)

**Comment by ReaJason** [comment]
请尝试重试，这个是被验证码挡住了 #93

**Comment by glorysaladin** [comment]
> 请尝试重试，这个是被验证码挡住了 #93

是说加上几次重试可以消除验证码吗？

**Comment by ReaJason** [comment]
> > 请尝试重试，这个是被验证码挡住了 #93
> 
> 是说加上几次重试可以消除验证码吗？

我刚试了，多尝试几次，会有那么一次没有验证码，这个挺玄学的

**Comment by glorysaladin** [comment]
> > > 请尝试重试，这个是被验证码挡住了 #93
> > 
> > 
> > 是说加上几次重试可以消除验证码吗？
> 
> 我刚试了，多尝试几次，会有那么一次没有验证码，这个挺玄学的

好吧。 另外想请教下有置顶自己的评论的接口吗？

**Comment by chenyucheng0503** [comment]
请问解决了吗？从昨晚开始就一直验证码，尝试很多次都没有解决

**Comment by glorysaladin** [comment]
> 请问解决了吗？从昨晚开始就一直验证码，尝试很多次都没有解决

你这里解决了吗， 一样需要验证码了。 几个账号都是。

**Comment by hjhjhghghg** [comment]
> > 请问解决了吗？从昨晚开始就一直验证码，尝试很多次都没有解决
> 
> 你这里解决了吗， 一样需要验证码了。 几个账号都是。

尝试上代理了吗

**Comment by glorysaladin** [comment]
> > > 请问解决了吗？从昨晚开始就一直验证码，尝试很多次都没有解决
> > 
> > 
> > 你这里解决了吗， 一样需要验证码了。 几个账号都是。
> 
> 尝试上代理了吗

没加代理，我查查怎么加代理。
